FROM python:3.8-slim-buster

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5001/tcp
EXPOSE 5002/tcp

CMD [ "python3", "flask_api.py"]
